#!/bin/sh

set -e

PROJECT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
DOTNET_DIR="${DOTNET_DIR:-${PROJECT_DIR}/../.dotnet}"
SUPPORT_DIR="${OPENHV_SUPPORT_DIR:-${PROJECT_DIR}/../.openhv-support}"
SIMULATION_MAP="${1:-coldrage}"
SIMULATION_BOT="${SIMULATION_BOT:-rogue}"
SIMULATION_BOTS="${SIMULATION_BOTS:-${SIMULATION_BOT}}"
SIMULATION_HEADLESS="${SIMULATION_HEADLESS:-false}"
SIMULATION_SPEED="${SIMULATION_SPEED:-fastest}"
SIMULATION_SEED="${SIMULATION_SEED:-}"
SIMULATION_MAX_TICKS="${SIMULATION_MAX_TICKS:-}"
SIMULATION_SCENARIO_MODE="${SIMULATION_SCENARIO_MODE:-conflict}"
SIMULATION_OBSERVATION_HORIZON_TICKS="${SIMULATION_OBSERVATION_HORIZON_TICKS:-0}"
SIMULATION_STALEMATE_WINDOW_TICKS="${SIMULATION_STALEMATE_WINDOW_TICKS:-0}"
SIMULATION_STALEMATE_TERMINATES="${SIMULATION_STALEMATE_TERMINATES:-false}"
SIMULATION_COLLAPSE_POPULATION_THRESHOLD="${SIMULATION_COLLAPSE_POPULATION_THRESHOLD:-250}"
SIMULATION_COLLAPSE_STABILITY_THRESHOLD="${SIMULATION_COLLAPSE_STABILITY_THRESHOLD:-250}"
SIMULATION_DURATION="${SIMULATION_DURATION:-}"
SIMULATION_WATCHDOG_SECONDS="${SIMULATION_WATCHDOG_SECONDS:-120}"
SIMULATION_TELEMETRY_INTERVAL_TICKS="${SIMULATION_TELEMETRY_INTERVAL_TICKS:-0}"
SIMULATION_CIVILIZATION_PROFILE="${SIMULATION_CIVILIZATION_PROFILE:-balanced}"
SIMULATION_TRADE_ENABLED="${SIMULATION_TRADE_ENABLED:-true}"
SIMULATION_MATCH_ID="${SIMULATION_MATCH_ID:-simulation}"
SIMULATION_RESULT="${SIMULATION_RESULT:-}"
SIMULATION_GIT_COMMIT="${SIMULATION_GIT_COMMIT:-$(git -C "${PROJECT_DIR}" rev-parse --verify HEAD 2>/dev/null || printf unknown)}"

if [ -z "${SIMULATION_GIT_DIRTY:-}" ]; then
	if [ -n "$(git -C "${PROJECT_DIR}" status --porcelain 2>/dev/null)" ]; then
		SIMULATION_GIT_DIRTY=true
	else
		SIMULATION_GIT_DIRTY=false
	fi
fi

if [ ! -x "${DOTNET_DIR}/dotnet" ]; then
	echo "Local .NET SDK not found at ${DOTNET_DIR}." >&2
	exit 1
fi

mkdir -p "${SUPPORT_DIR}"

PATH="${DOTNET_DIR}:${PATH}" \
DOTNET_ROOT="${DOTNET_DIR}" \
DOTNET_CLI_TELEMETRY_OPTOUT=1 \
exec "${PROJECT_DIR}/launch-game.sh" \
	"Engine.SupportDir=${SUPPORT_DIR}" \
	"Engine.Headless=${SIMULATION_HEADLESS}" \
	"Engine.DeterministicSimulation=true" \
	"Launch.Simulation=true" \
	"Launch.Map=${SIMULATION_MAP}" \
	"Launch.SimulationBot=${SIMULATION_BOT}" \
	"Launch.SimulationBots=${SIMULATION_BOTS}" \
	"Launch.SimulationSpeed=${SIMULATION_SPEED}" \
	"Launch.SimulationSeed=${SIMULATION_SEED}" \
	"Launch.SimulationMaxTicks=${SIMULATION_MAX_TICKS}" \
	"Launch.SimulationScenarioMode=${SIMULATION_SCENARIO_MODE}" \
	"Launch.SimulationObservationHorizonTicks=${SIMULATION_OBSERVATION_HORIZON_TICKS}" \
	"Launch.SimulationStalemateWindowTicks=${SIMULATION_STALEMATE_WINDOW_TICKS}" \
	"Launch.SimulationStalemateTerminates=${SIMULATION_STALEMATE_TERMINATES}" \
	"Launch.SimulationCollapsePopulationThreshold=${SIMULATION_COLLAPSE_POPULATION_THRESHOLD}" \
	"Launch.SimulationCollapseStabilityThreshold=${SIMULATION_COLLAPSE_STABILITY_THRESHOLD}" \
	"Launch.SimulationDuration=${SIMULATION_DURATION}" \
	"Launch.SimulationWatchdogSeconds=${SIMULATION_WATCHDOG_SECONDS}" \
	"Launch.SimulationTelemetryIntervalTicks=${SIMULATION_TELEMETRY_INTERVAL_TICKS}" \
	"Launch.SimulationCivilizationProfile=${SIMULATION_CIVILIZATION_PROFILE}" \
	"Launch.SimulationTradeEnabled=${SIMULATION_TRADE_ENABLED}" \
	"Launch.SimulationMatchId=${SIMULATION_MATCH_ID}" \
	"Launch.SimulationGitCommit=${SIMULATION_GIT_COMMIT}" \
	"Launch.SimulationGitDirty=${SIMULATION_GIT_DIRTY}" \
	"Launch.SimulationResult=${SIMULATION_RESULT}"
